# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da44db6ec42b4729db3ad37af7ebdade9a6fb8df49930f009575db92b514e92fb35d7957292740eaa2ee72b4cf659dfff50ccb11ceba6931d8c5f749c92d3c5

test:
  secret_key_base: 5294171c5dc42ceb5232f0d949bf877662025c5fe91170ea2dce6e2deb088768e540ade397621201e918b837434d256fbac497d21fd19b9179c880c1fa357dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
